apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  labels:
    name: nodeport-label
spec:
  selector:
    app: myapp1
  type: NodePort
  ports:
  - name: http
    port: 80 
    targetPort: 80 
    nodePort: 30033 
    protocol: TCP
